---
# tasks file for ansible-role-openshift-custom-login-page

  - name: Get timestamp
    local_action: command date +"%Y%m%d_%H%M%S"
    register: date

  - name: Backup original master-config.yaml file
    copy: src="{{openshift_master_conf_dir}}/master-config.yaml" dest="{{openshift_master_conf_dir}}/master-config.yaml_{{date.stdout}}" backup="yes"

  - name: Check if image exist
    stat: "path={{logo_img}} "
    delegate_to: "{{groups.masters[0]}}"
    register: stat_logo_img_exist

  - name: If the logo_img does not exit, it fails
    fail: msg="logo image does not exist, please check it"
    when: stat_logo_img_exist.stat.exists == false

  - name: Create temp dir if it does not exist
    file: "path={{temp_dir}} state=directory"
    delegate_to: "{{groups.masters[0]}}"

  - name: Create login page dir if it does not exist
    file: "path={{stylesheet_base_dir}} state=directory"

  - name: Create CSS/Image folder
    file: path={{item}} state=directory
    with_items:
        - "{{stylesheet_base_dir}}/css"
        - "{{stylesheet_base_dir}}/images"

  - name: Copy web console logo under {stylesheet_base_dir}}/images
    copy: src={{logo_img}} dest="{{stylesheet_base_dir}}/images" remote_src="true" force={{force}}

  - name: Copy css file under {stylesheet_base_dir}}/css
    template: src=extensions.css.j2 dest="{{stylesheet_base_dir}}/css/extensions.css" force={{force}}

  - name: Webconsole configuration txt file to /etc/origin/master
    template: src=webconsole_conf.txt.j2 dest={{stylesheet_base_dir}}/webconsole_conf.txt force={{force}}
    delegate_to: "{{groups.masters[0]}}"
    run_once: true

  - name: Check the configuration exist in master-config.yaml
    shell: grep extensions {{openshift_master_conf_dir}}/master-config.yaml|wc -l
    delegate_to: "{{groups.masters[0]}}"
    register: extension_conf_exist
    run_once: true
   
  - name: Configure master-config.xml to load new logo for web console
    shell: sed -e "$(grep -n assetConfig {{openshift_master_conf_dir}}/master-config.yaml |cut -d':' -f1)r {{stylesheet_base_dir}}/webconsole_conf.txt" -i {{openshift_master_conf_dir}}/master-config.yaml
    when: "{{extension_conf_exist.stdout}} == 0"
    delegate_to: "{{groups.masters[0]}}"
    run_once: true

  - name: Copy new master-config.yaml to all master servers
    synchronize:  src={{openshift_master_conf_dir}}/master-config.yaml dest={{openshift_master_conf_dir}}/master-config.yaml
    delegate_to: "{{groups.masters[0]}}"
    when: "{{inventory_hostname != groups.masters[0]}} and ( {{extension_conf_exist.stdout}} == 0  or {{force}} == true)"

  - name: Clean temp files in local
    file: path={{item}} state=absent
    with_items:
        - "{{temp_dir}}/{{stylesheet_base_dir}}/webconsole_conf.txt"
    delegate_to: "{{groups.masters[0]}}"
    run_once: true

